In [63]:
import pandas as pd
import numpy as np
import math
df = pd.read_csv('C:\\Users\\user_PC\\Desktop\\mortality.txt', sep="\t", header=0)
#data.columns = ['location', 'town', 'mortality', 'hardness']
print(df.head(10), df.columns)

  location         town  mortality  hardness
0    South         Bath       1247       105
1    North   Birkenhead       1668        17
2    South   Birmingham       1466         5
3    North    Blackburn       1800        14
4    North    Blackpool       1609        18
5    North       Bolton       1558        10
6    North       Bootle       1807        15
7    South  Bournemouth       1299        78
8    North     Bradford       1637        10
9    South     Brighton       1359        84 Index(['location', 'town', 'mortality', 'hardness'], dtype='object')


определим дов интервалы для смерности в больших городах по данной нам выборке (всей выборке)

In [64]:
#df = df[df["location"] == 'South']
n = (len(df))
std_hardness = df.std()['hardness']
std_mortality = df.std()['mortality']
print('размер выборки={}, СКО жесткости воды={}, СКО смертности={}'.format(n, std_hardness, std_mortality))

размер выборки=26, СКО жесткости воды=40.36068155252851, СКО смертности=140.26917529686108


In [65]:
mean_hardness = df.mean()['hardness']
mean_mortality = df.mean()['mortality']
print('среднее жесткости воды={}, среднее смертности={}'.format(mean_hardness, mean_mortality))

среднее жесткости воды=69.76923076923077, среднее смертности=1376.8076923076924


#### доверительный интервал. поскольку реальная дисперсия ген выборки неизвестна, исп т критерий $$\bar{X}_n \pm t_{1-\frac{\alpha}{2}} \frac{S}{\sqrt{n}}$$


In [66]:
from statsmodels.stats.weightstats import  _tconfint_generic
mean_std = std_hardness/math.sqrt(n)
print ("sgd model mean auc 95%% confidence interval", _tconfint_generic(mean_hardness, mean_std,
                                                                       n - 1,
                                                                       0.05, 'two-sided'))

sgd model mean auc 95%% confidence interval (53.467198692036106, 86.07126284642544)


## доверительный интервал доли
определеим дов интервал правильно (по Вилсону) чего-то там у генеральной выборки, если у локальной выборки 1 случай чего-то там на 50 человек


In [26]:
from statsmodels.stats.proportion import proportion_confint
print(proportion_confint(1, 50, method = 'wilson'))

(0.5730534379509052, 0.7543687726587197)


теперь определим неправильно по нормальному распределению

In [4]:
import numpy as np
import math
import scipy.stats as st

z_score_95 = st.norm.ppf(.975)
print(z_score_95)
boarder_95 = z_score_95*math.sqrt(0.02*0.98/50)
print((0.02-boarder_95), (0.02+boarder_95))

2.9677379253417944
-0.038758213130223 0.078758213130223


 По данным опроса, 75% работников ресторанов утверждают, что испытывают на работе существенный стресс, оказывающий негативное влияние на их личную жизнь. Крупная ресторанная сеть опрашивает 100 своих работников, чтобы выяснить, отличается ли уровень стресса работников в их ресторанах от среднего. 67 из 100 работников отметили высокий уровень стресса.

In [9]:
import scipy
p_value = scipy.stats.binom_test(67, n=100, p=0.75, alternative='less',)
print(p_value)

0.044596325212681504


Для участка заповедника размером 200х200 м имеется информация о координатах сосен (sn — координата в направлении север-юг, we — в направлении запад-восток, обе от 0 до 200).

Загрузите данные, поделите участок на 5х5 одинаковых квадратов размера 40x40 м, посчитайте количество сосен в каждом квадрате (чтобы получить такой же результат, как у нас, используйте функцию scipy.stats.binned_statistic_2d).

Если сосны действительно растут равномерно, какое среднее ожидаемое количество сосен в каждом квадрате?

In [1]:
import pandas as pd
import numpy as np
import math
df = pd.read_csv('C:\\Users\\user_PC\\Desktop\\pines.txt', sep="\t", header=0)
print(df.head(10), df.columns)

      sn    we
0  200.0   8.8
1  199.3  10.0
2  193.6  22.4
3  167.7  35.6
4  183.9  45.4
5  182.5  47.2
6  166.1  48.8
7  160.7  42.1
8  162.9  29.0
9  166.4  33.6 Index(['sn', 'we'], dtype='object')


In [2]:
print(df.describe())

               sn          we
count  584.000000  584.000000
mean    98.735274  113.829281
std     56.523154   49.810725
min      0.000000    0.000000
25%     52.050000   79.125000
50%    101.450000  121.900000
75%    149.400000  149.725000
max    200.000000  200.000000


In [3]:
#все параметры от 0 до 200. тогда при делении на кважраты 40*40 будет по 5 квадратов в каждом направллении
#заведем список из 25 значений, которые соответствую количеству деревьев в квадрате
sn = df['sn'].values.tolist()
we = df['we'].values.tolist()
values = list(zip(sn,we))
print('средняя плотность дереьвев в лесу', len(sn)/25)
bin_list = [0, 40, 80, 120, 160, 200]
from scipy import stats
ret = stats.binned_statistic_2d(sn, we, bin_list, 'count', bins=[bin_list,bin_list])
print('распределение по квадратам',ret[0])


средняя плотность дереьвев в лесу 23.36
распределение по квадратам [[18. 26. 29. 25. 20.]
 [14. 12. 22. 34. 25.]
 [12. 24. 15. 50. 37.]
 [ 8. 19. 31. 50.  7.]
 [ 7.  8. 37. 27. 27.]]


C:\Users\user_PC\Anaconda3\lib\site-packages\scipy\stats\_binned_statistic.py:607: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  result = result[core]


Чтобы сравнить распределение сосен с равномерным, посчитайте значение статистики хи-квадрат для полученных 5х5 квадратов относительно гипотезы о равномерном распределении деревьев по квадратам.

In [8]:
from scipy import stats
flat_distribution = [int(x) for x in ret[0].ravel()]
generated_distribution = [23.36]*len(flat_distribution)

std_ = np.std(flat_distribution, ddof = 1)
mean_ = np.mean(flat_distribution)

stats.chisquare(flat_distribution, generated_distribution, ddof = 1)






Power_divergenceResult(statistic=150.58904109589042, pvalue=2.574669774967279e-20)

## доверительный интервал для разности долей (независимые выборки)

В пятилетнем рандомизированном исследовании Гарвардской медицинской школы 11037 испытуемых через день принимали аспирин, а ещё 11034 — плацебо. Исследование было слепым, то есть, испытуемые не знали, что именно они принимают.

За 5 лет инфаркт случился у 104 испытуемых, принимавших аспирин, и у 189 принимавших плацебо.

Постройте теперь 95% доверительный интервал для снижения вероятности инфаркта при приёме аспирина. Чему равна его верхняя граница?

$$\text{Доверительный интервал для }p_1 - p_2\colon \;\; \hat{p}_1 - \hat{p}_2 \pm z_{1-\frac{\alpha}{2}}\sqrt{\frac{\hat{p}_1(1 - \hat{p}_1)}{n_1} + \frac{\hat{p}_2(1 - \hat{p}_2)}{n_2}}$$

In [1]:
#p1 = это доля инфаркников в 1 выборке 
#p2 = это доля инфаркников в 2 выборке 
import numpy as np
import scipy.stats as st

def proportions_confint_diff_ind(cases1, cases2 ,sample1, sample2, alpha = 0.05):    
    z = st.norm.ppf(.975)#scipy.stats.norm.ppf((1 - alpha)/ 2)   
    p1 = cases1 / sample1
    p2 = cases2 / sample2
    
    left_boundary = abs(p1 - p2) - z * np.sqrt(p1 * (1 - p1)/ sample1 + p2 * (1 - p2)/ sample2)
    right_boundary = abs(p1 - p2) + z * np.sqrt(p1 * (1 - p1)/ sample1 + p2 * (1 - p2)/ sample2)
    
    return (left_boundary, right_boundary)
print(proportions_confint_diff_ind(104, 189 ,11037, 11034, alpha = 0.05))

(0.004687750675049439, 0.010724297276960124)


Продолжим анализировать данные эксперимента Гарвардской медицинской школы.

Для бернуллиевских случайных величин X∼Ber(p) часто вычисляют величину p/(1-p) 

189/(11034−189) ≈0.0174

Для величины, характеризующей во сколько раз понижаются шансы инфаркта при регулярном приёме аспирина надо построить 95% доверительный интервал с помощью бутстрепа. Чему равна его нижняя граница? 

In [2]:
import numpy as np
import pandas as pd
np.random.seed(0)


def get_bootstrap_samples(data, n_samples):
    'n_samples - количество псевдовыборок c возвращением -элементы в псевдовыборке могут повторяться'
    'data - pd.Series(генеральной совокупности)'
    'функция возвращает список выборок длиной data в количестве n_samples'
    indices = np.random.randint(0, len(data), (n_samples, len(data))) 
    samples = []
    for i in indices:
        samples.append(data[i])
    return samples


aspirin_set = [1]*104 +[0]*10933
placebo_set = [1]*189+ [0]*10845

aspirin_set = pd.Series(aspirin_set, index = range(0, len(aspirin_set)))
placebo_set = pd.Series(placebo_set, index = range(0, len(placebo_set)))



aspirin_set = list(map(lambda x: (sum(x)/len(x)/(1 - sum(x)/len(x))), get_bootstrap_samples(aspirin_set, 1000)))
placebo_boot_set = list(map(lambda x: (sum(x)/len(x)/(1 - sum(x)/len(x))), get_bootstrap_samples(placebo_set, 1000)))
infarct_update = [i/j for i,j in zip(placebo_boot_set, aspirin_set)]

def stat_intervals(stat, alpha):
    'alpha [0,1], stat - список наших статистик из бутстрепа'
    boundaries = np.percentile(stat, [100 * alpha / 2., 100 * (1 - alpha / 2.)])
    return boundaries

print ("95% confidence interval",  stat_intervals(infarct_update, 0.05))

95% confidence interval [1.44419465 2.34321168]
